### ISSUE TITLE
no instructions

### ISSUE THREAD

**Issue by snowywish** [billcoding/vip-video-downloader#2]
How to install this tool ?
and how to use command?
there is no instructions pls help me

**Comment by billcoding** [comment]
Hi, you have two ways to install.

1. Use Go SDK
```go install github.com/billcoding/vip-video-downloader@latest```

![image](https://user-images.githubusercontent.com/21271780/148312670-d263b25d-bb75-41c1-b19f-e204a40adcb4.png)


2. Download from releases
- Go to ```https://github.com/billcoding/vip-video-downloader/releases```
- Click latest version
- Download your OS binrary file

**Comment by billcoding** [comment]
Hi, type `vip-video-downloader -h`.

![image](https://user-images.githubusercontent.com/21271780/148312909-4aa6d945-31f0-4e0d-8588-3892dca25892.png)

**Comment by snowywish** [comment]
vip-video-downloader -h https://v.youku.com/v_show/id_XNDk3NTAwMTA3Ng
this command is not working for me

**Comment by billcoding** [comment]
You can do by steps:
`vip-video-downloader download -V "https://v.youku.com/v_show/id_XNDk3NTAwMTA3Ng"`
![image](https://user-images.githubusercontent.com/21271780/148638749-a164ad8f-8d55-4896-89b9-c74843e65ffd.png)

**Comment by snowywish** [comment]
thank you so much
i have one more question how to download video in 1080p
this only downloaded in 540p

**Comment by billcoding** [comment]
Please go to #1 .
