### ISSUE TITLE
youku

### ISSUE THREAD

**Issue by huoshenw** [billcoding/vip-video-downloader#4]
下载前6分钟后出现
[failed] request https://ykugc.cp31.ott.cibntv.net/ffsir~2022-01-25/67756D6080932713CFC02204E/0300090000604B080ACF6392EFD127BF24B065-AC93-4851-8378-51E49077AA6A-01566.ts?expire=18000&psid=446ea252c4d2e31feb90ed073fddde3d43346&ups_ts=1643372825&vid=XMjIwNDU5NjE4NA&vkey=A33f323c0214512312d1942e6ef32f9bb, http error: status code 403
我有优酷VIP账号 该如何使用cookie 下载VIP视频

**Comment by huoshenw** [comment]
总时长4小时50分钟 但是合并了一下ts文件发现只有4小时 下载不全
第二次尝试连ts文件都不下载了

**Comment by billcoding** [comment]
> 下载前6分钟后出现 [failed] request https://ykugc.cp31.ott.cibntv.net/ffsir~2022-01-25/67756D6080932713CFC02204E/0300090000604B080ACF6392EFD127BF24B065-AC93-4851-8378-51E49077AA6A-01566.ts?expire=18000&psid=446ea252c4d2e31feb90ed073fddde3d43346&ups_ts=1643372825&vid=XMjIwNDU5NjE4NA&vkey=A33f323c0214512312d1942e6ef32f9bb, http error: status code 403 我有优酷VIP账号 该如何使用cookie 下载VIP视频

#### 你可以按如下尝试：
- 使用Chrome浏览器的开发者工具(F12)->网络(Network)->筛选(Filter)
![image](https://user-images.githubusercontent.com/21271780/152929084-ad5d23c9-03b6-47a3-951a-e853bd7f1835.png)
- 复制m3u8的URL
- 使用`vip-video-downloader`下载即可
```vip-video-downloader d -V -m "M3U8地址" ```

**Comment by billcoding** [comment]
> 总时长4小时50分钟 但是合并了一下ts文件发现只有4小时 下载不全 第二次尝试连ts文件都不下载了

这可能是资源的问题。

**Comment by huoshenw** [comment]
![image](https://user-images.githubusercontent.com/26380831/152935879-6461b3a9-f9a6-4078-b0c9-e15f604a0e9b.png)
下载后合并失败

**Comment by snowywish** [comment]
Facing same problem

**Comment by billcoding** [comment]
这似乎不是合并报错的，是FFmpeg的问题，合并是在此动作的前一个步骤。
