### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by larryqiann** [billcoding/vip-video-downloader#5]
I am attempting to use this on macOS 12.1 Monterey M1, and I get this error:

runtime error: invalid memory address or nil pointer dereference

I am attempting to run the command 

./vip-video-downloader download https://v.qq.com/x/cover/mzc002008loh4qx.html 

Is this a known issue with the application?

Thank you

**Comment by billcoding** [comment]
Thanks for summitting this issue.

I will fix it.
