### ISSUE TITLE
not able to download qq site (m3u8)

### ISSUE THREAD

**Issue by snowywish** [billcoding/vip-video-downloader#6]
vip-video-downloader download -V "https://v.qq.com/x/cover/mzc00200opqzg5p.html"
[m3u8]https://subtitle.apdcdn.tc.qq.com/pcdnts.tc.qq.com/https://v.qq.commoviets.tc.qq.com/A0n2LfGu7GtpPpUufWnC1xrbtf_B-xdrbrmNWhdd5J24/uwMROfz2r55goaQXGdGnCWde64jX5uBE81GpbfuWy4ncgW14/svp_50112/2ec9MYARnwkOIbuCVvfLMxSFYaLgVKIeq2F_bLOho97V6hGRx-xVYHEOEGRDp7ef4Ux_vOVUHseP67ao-RSVJp3kEpGMuLl5rf9ANekynuphirLe4yu_Uygadhv-qmr_1pxFibIsVcKALum1QqoSDJYkQka5X9lfaEJd6PIjMopZpSRBSQC8-A/gzc_1000102_0b53yeabwaaajeagimjqezrmbqoddpgqah2a.f321004.ts.m3u8?ver=4
request m3u8 URL failed: http error: status code 404

**Comment by billcoding** [comment]
Retry some times.
